substitutions:
  _REGION: us-central1
  _REPO: idso-apps
  _IMAGE_NAME: app-generator-v2-backend
  _IMAGE_TAG: latest
  _SERVICE: idso-app-generator-v2-backend-dev

steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${_IMAGE_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:latest
      - backend

  - name: gcr.io/cloud-builders/docker
    id: push-tag
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${_IMAGE_TAG}

  - name: gcr.io/cloud-builders/docker
    id: push-latest
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${_IMAGE_TAG}
      - --region=${_REGION}
      - --platform=managed
      - --quiet

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${_IMAGE_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:latest

options:
  logging: CLOUD_LOGGING_ONLY
